//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kayit
    {
        public int kayitid { get; set; }
        public string msjid { get; set; }
        public string kisiid { get; set; }
    
        public virtual kisiler kisiler { get; set; }
        public virtual mesajlar mesajlar { get; set; }
    }
}
